windowrule {
  name = gamescope
  match:class = gamescope

  monitor = DP-3
  content = game
}

#################
## ARC Raiders ##
#################
windowrule {
  name = arc-raiders
  match:title = ARC Raiders

  monitor = DP-3
  content = game
}

