general {
  # Doesn't seem to work for now
  # lock_cmd = pidof hyprlock || hyprlock # avoid starting multiple hyprlock instances.
  before_sleep_cmd = loginctl lock-session # lock before suspend.
  after_sleep_cmd = hyprctl dispatch dms on # to avoid having to press a key twice to turn on the display.
}

listener {
  timeout = 300 # 10min
  on-timeout = brightnessctl -s set 10 # Brightness 10%
  on-resume = brightnessctl -r # Brightness restore
}

listener {
  timeout = 600 # 10min
  on-timeout = hyprctl dispatch dpms off # Turn off screen
  on-resume = hyprctl dispatch dpms on && brightnessctl -r # Turn on screen and restore brightness
}

listener {
  timeout = 1200 # 20min
  on-timeout = loginctl lock-session # Lock screen
}

# Sleeping doesn't seem to work for now
# listener {
#   timeout = 3600 # 1hour
#   on-timeout = systemctl suspend # sleep
# }
